### ISSUE TITLE
VitalDB BP Source

### ISSUE THREAD

**Issue by JoAllg** [pulselabteam/PulseDB#1]
For MIMIC III it says that SBP and DBP are extracted from the continous ABP signal.
As for VitalDB the Solar 8000m Device seems to have recorded BP from different sources: femoral, invasive, non-invasive. Which of those signals are used in PulseDB ?

**Comment by WeinanWang-RU** [comment]
When we retrieve ECG, PPG and arterial blood pressure (ABP) from VitalDB, we search for these IDs:
'SNUADC/ECG_II' (Lead-II ECG)
'SNUADC/PLETH' (PPG)
'SNUADC/ART' (ABP)
You can find these IDs from: https://vitaldb.net/dataset/#h.foizq7qqcyzk
All of these are of type "waveform", not "numeric". So the answer to your question is that we did not use the numerical BP readings in VitalDB. The SBP and DBP are extracted and segment-averaged from the ABP waveform during signal processing, in the same way as MIMIC-III.

**Comment by JoAllg** [comment]
Thank you for your reply. I have been trying to evaluate the source quality of the signals/data and your information clarifies it for the VitalDB source. Happy to see that the source seems to be the more realiable ART.
