### ISSUE TITLE
Inconsistent Info_Files and Segment_Files?

### ISSUE THREAD

**Issue by MSSRPRAD** [pulselabteam/PulseDB#14]
I am trying to generate the subsets as described in the PulseDB Paper.

I have downloaded all the required .mat files and am trying to select the required Segments using the Info_Files.

For eg, Info_Files/Train_Info.mat has 902160 rows, with Subj_Name and Subj_SegIDX columns which I suppose correspond to the SubjectID and SegmentID columns in the segment (removing the _0 and _1 appended in the Info_Files).

I notice that on extracting the data and doing an inner join on the tables represented by the Segment_Files/*/*.mat and Info_Files/Train_Info.mat, I get only 561734 rows instead of the 902160 rows in Train_Info.mat.

Analyzing further, I see that this is because a lot of rows where the Subj_SegIDX column values are not existing in the Segment_Files's SegmentID column at all.

For example, considering p000001, we have the following Subj_SegIDX values:

2.0, 4.0, 5.0, ......

While the corresponding segment file has the following SegmentID values:
55.0, 63.0, 64.0, .....

This can be seen replicated by the following code:

```python
import h5py
import numpy as np
f = h5py.File("Info_Files/Train_Info.mat")
arr = np.array(f[f['Train_Subset']['Subj_SegIDX'][0][436819]])
--------------------------------------------------
>>> arr                                                           
array([[2.]])
```

If we see the corresponding Segment File (where the data is sorted acc to SegmentID column,

```python
import h5py
import numpy as np
f = h5py.File("Segment_Files/PulseDB_Vital/p000001.mat")
np.array(f[f['Subj_Wins']['SegmentID'][0][0]])
-----------------------------------------------
>>> np.array(f[f['Subj_Wins']['SegmentID'][0][0]])
array([[55.]])
```

Or, the Segment ID's start from 55. There is no segment with ID=2.

Am I using the wrong Segment Files or the wrong Info Files? (I have downloaded all from the v2 version box or google drive.)

Or is my approach itself towards generating the subsets wrong?

Would appreciate some help here. Thank you. @WeinanWang-RU

**Comment by MSSRPRAD** [comment]
Subj_SegIDX is the relative index inside that particular segment file, not the segment id. Making this change to the SQL Query resolves the problem, and gives me the correct number of rows.

I am closing this issue as the issue is resolved.

**Comment by WeinanWang-RU** [comment]
Your last comment is correct.

You can create the subsets by directly using the provided MATLAB script, `Generate_Subsets.m`.

You can see how this script retrieve rows in the data files by using information in the info file: it index columns in the data file using the Subj_SegIDX in the info file:

https://github.com/pulselabteam/PulseDB/blob/db0824f18d9a462458e46fe94c31283a93a5c0d5/Generate_Subsets.m#L96-L100
