### ISSUE TITLE
Clarification needed on VitalDB dataset in PulseDB

### ISSUE THREAD

**Issue by amsinha9** [pulselabteam/PulseDB#2]
I didn't find any documentation on the data in the VitalDB dataset within PulseDB. A few clarification questions:

- What does `ABP_Lag` mean and do we need to account for it when analyzing the data? I'm assuming this lag comes from here in the paper, "PPG-ABP correlation analysis: The PPG and the ABP signals are first aligned using a lag that yields the highest cross correlation between the two signals to compensate the phase difference of the two signals and the inter-signal misalignment in the MIMIC-III database. Next, the Pearson’s correlation coefficient between the aligned signals is calculated, and the segment is rejected if the correlation coefficient is <0.9, as suggested in 46 ".
- What is `CaseID`? It appears that `CaseID` is not the same as `SubjectID`, as there are more unique values for `CaseID` than `SegmentID`. How is this mapping done?

**Comment by WeinanWang-RU** [comment]
I added the [Supplementary Material](https://github.com/pulselabteam/PulseDB/blob/main/Supplementary%20Materials.pdf) of the paper to this repository (which is part of the paper but might be hard to find on the Frontiers website). Can you check it out and see if that addresses your problems?

**Comment by amsinha9** [comment]
This supplementary material addresses my questions. Thanks!
