### ISSUE TITLE
Data Unzipping

### ISSUE THREAD

**Issue by Khaled-Mohammed-Abdelgaber** [pulselabteam/PulseDB#3]
I am facing an issue when I try to unzip folders of data for example this folder PulseDB_Vital.zip.002 is ended with a number so I can not use the WinRAR program to unzip it. I have tried to rename the folder to become PulseDB_Vital.zip . then I used the WinRAR program to unzip it but I get an error message saying that the folder is damaged.

**Comment by WeinanWang-RU** [comment]
These are not meant to be renamed, and you cannot use only one of the files to get part of the data. The 001,002,... are extensions standing for parts of subsection compressed files created from one single folder, which requires downloading all parts before usable. If all part files have been downloaded without corruption and have been put under the same folder, then with a supported unzipping software such as 7zip, unzipping any of the files will give you the folder that was compressed. 

If you want to download part of the dataset, please  consider trying the links provided under **Update_2023_03_02** in [Readme.md](https://github.com/pulselabteam/PulseDB/blob/main/README.md), which gives you access to individual files in PulseDB.

**Comment by Khaled-Mohammed-Abdelgaber** [comment]
thank you for this clear explanation

**Comment by Khaled-Mohammed-Abdelgaber** [comment]
@WeinanWang-RU can you tell me how to get the corresponding disease of each subject in the dataset?

**Comment by WeinanWang-RU** [comment]
> @WeinanWang-RU can you tell me how to get the corresponding disease of each subject in the dataset?

Sorry, I cannot comment on that since the disease of each subject is outside the scope of this paper. Please close this issue if I have addressed your question with respect to data unzipping. Thanks.
