### ISSUE TITLE
How can i get the corresponding disease of each subject in the dataset??

### ISSUE THREAD

**Issue by Khaled-Mohammed-Abdelgaber** [pulselabteam/PulseDB#4]

**Comment by WeinanWang-RU** [comment]
Information with respect to the disease of each subject is not part of **PulseDB** and is outside the scope of this publication. 

However, there are ways that you can look them up by yourself via the `SubjectID` provided in **PulseDB**.

For example, the first file in the **PulseDB_MIMIC**  folder is `p000160.mat`. Segments in this file are from one subject whose `Subject_ID` in the **MIMIC-III Clinical Database** is p000160. So you can look up this ID in the **MIMIC Clinical Database** to find related information corresponding to this subject. Refer to [MIMIC-III matched subset](https://physionet.org/content/mimic3wdb-matched/1.0/) for more information.

As for the **PulseDB_Vital** folder, the file names are from `p000001.mat` to `p006090.mat`, which corresponds to `subjectid` from `1` to `6090` in the **VitalDB** dataset. So you can retrieve other information relating to the subject with the ID. Refer to [VitalDB APIs](https://vitaldb.net/dataset/?query=api) and [VitalDB Case API](https://api.vitaldb.net/cases) for more information.

**Comment by Khaled-Mohammed-Abdelgaber** [comment]
thanks for your response. really good job
