### ISSUE TITLE
Can you provide python script that loading the dataset? 

### ISSUE THREAD

**Issue by Kukty** [pulselabteam/PulseDB#5]
Hello, Thanks for you amazing work and dataset, I want to run my own bp predict model on your dataset, can you provide Python script such as Pytorch Dataset or Dataloader, which can help me more simply to load the model and compare with your banch mark

**Comment by WeinanWang-RU** [comment]
I added a sample code to [README.md](https://github.com/pulselabteam/PulseDB/blob/main/README.md)

**Comment by Kukty** [comment]
> I added a sample code to [README.md](https://github.com/pulselabteam/PulseDB/blob/main/README.md)

Really appreciate you!
